# Xamarin.Android
# Build a Xamarin.Android project.
# Add steps that test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

pool:
  vmImage: 'macOS 10.13'

variables:
  buildConfiguration: 'Release'
  outputDirectory: '$(build.binariesDirectory)/$(buildConfiguration)'

steps:
- task: NuGetToolInstaller@0

- task: NuGetCommand@2
  inputs:
    restoreSolution: '**/*.sln'

- task: XamarinAndroid@1
  inputs:
    projectFile: '**/*droid*.csproj'
    outputDirectory: '$(outputDirectory)'
    configuration: '$(buildConfiguration)'
    
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*.UnitTests/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

# Android Signing
# Sign and align Android APK files
- task: AndroidSigning@3
  inputs:
    apkFiles: '**/*.apk' 
    apksign: true # Optional
    apksignerKeystoreFile: 'tp2.keystore' # Required when apksign == True
    apksignerKeystorePassword: 'qwerty' # Optional
    apksignerKeystoreAlias: tp2.key # Optional
    apksignerKeyPassword: 'qwerty' # Optional
    apksignerArguments: '--verbose' # Optional
    #apksignerFile: # Optional
    zipalign: true # Optional
    #zipalignFile: # Optional
    
#- task: CopyFiles@2
#  inputs:
#    contents: '**/*.apk'
#    targetFolder: '$(build.artifactStagingDirectory)'

#- task: PublishBuildArtifacts@1

- task: FtpUpload@1
  inputs:
    credentialsOption: 'inputs' # Options: serviceEndpoint, inputs
    #serverEndpoint: # Required when credentialsOption == ServiceEndpoint
    serverUrl: 'ftp://infoazureftp.cegep-ste-foy.qc.ca' # Required when credentialsOption == Inputs
    username: '$(cegep.login)' # Required when credentialsOption == Inputs
    password: '$(cegep.password)' # Required when credentialsOption == Inputs
    rootDirectory: '$(Build.SourcesDirectory)'
    filePatterns: '**/*.apk' 
    remoteDirectory: '/$(Build.Repository.Name)' 
    #clean: false 
    #cleanContents: false # Required when clean == False
    #overwrite: true 
    #preservePaths: false 
#trustSSL: false
